kind: pipeline
name: pull_request

trigger:
  event:
    - pull_request

steps:
  - name: install
    image: node
    commands:
      - node --version
      - yarn --version
      - yarn install
      - yarn bootstrap

  - name: lint
    image: node
    commands:
      - yarn lint

  - name: test
    image: node
    commands:
      - yarn test
